#!/bin/bash

DOCKER_USER=soolaugust

CGO_ENABLED=0 GOOS=linux go build -mod=vendor -a -installsuffix cgo -o lxcfs-admission-webhook
docker build --no-cache -t registry.cn-hangzhou.aliyuncs.com/${DOCKER_USER}/lxcfs-admission-webhook:v1 .
rm -rf lxcfs-admission-webhook

docker push registry.cn-hangzhou.aliyuncs.com/${DOCKER_USER}/lxcfs-admission-webhook:v1
